### ISSUE TITLE
About submit button

### ISSUE THREAD

**Issue by rcalfredson** [yanfengliu/turkey#5]
Hey to Yanfeng et al,

Regarding the submit button, I know that it gets added separately to the HTML in `localDemo.html`, but inside the file `MTurk.html`, how does the submit button get added to the page? For instance, I see on [this line](https://github.com/yanfengliu/turkey/blob/9359e3da5cbafb1488b3bccf4df6333ce3c0fedc/MTurk.html#L249) that the element already exists. I inferred that the Mechanical Turk code must append an element called `submitButton` to the page under the existing use case, or something similar?

The reason I am curious is that I am making some modifications to this code so it can run in Amazon SageMaker for a private workforce instead of via Mechanical Turk, and was trying to figure out some details of the app's design for its current platform.

Thank you.

**Comment by rcalfredson** [comment]
Figured out one solution with the aid of this [blog post](https://aws.amazon.com/blogs/machine-learning/build-a-custom-data-labeling-workflow-with-amazon-sagemaker-ground-truth/). Their idea is to add a `<crowd-form>` element to the bottom of the HTML for the page, as follows:
```html
<crowd-form>
    <input name="annotations" id="annotations" type="hidden">

    <!-- Prevent crowd-form from creating its own button -->
    <crowd-button form-action="submit" style="display: none;"></crowd-button>
</crowd-form>
```

Then make the actual submit button a `<crowd-button>` element, like this:
```html
<crowd-button class="btn btn-success" id="submitButton">Submit</crowd-button>
```

Finally, couple the physical button with the hidden one that will control the annotation data sent to the post-labeling lambda, like this:
```html
<script id="linkSubmitBtns" type="text/javascript">
    document.querySelector('crowd-form').onsubmit = function () {
        document.getElementById('annotations').value = JSON.stringify(annotations);
    };

    document.getElementById('submitButton').onclick = function () {
        document.querySelector('crowd-form').submit();
    };
</script>
```

**Comment by yanfengliu** [comment]
@rcalfredson Hey, thanks for using turkey! Glad you were able to figure out a solution. In general, [Crowd HTML Elements](https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_HTMLCustomElementsArticle.html) is a great library to use if you want to create annotation GUI on Amazon platforms.
