### ISSUE TITLE
 Cannot start a polygon annotation 

### ISSUE THREAD

**Issue by ZhanqiZhang66** [yanfengliu/turkey#6]
Hi Yanfeng,

When I copy the Mturk.html into a custom HIT in the Amazon Turk Requester, the polygon annotation seems to be not working as expected.

For example, I clicked "tree" to annotate on the left. As I clicked "sky" to move on to annotate on the right side, there is an edge connecting the first "tree" and the "sky". I also couldn't figure out how to get the polygon filled with color as what you did in the demo (the middle tree). Did I do something wrong here?

I would appreciate it if you could please help me with it and I look forward to your response!
![thumbnail_Outlook-h15k2izz](https://user-images.githubusercontent.com/31415280/102913749-ccd66680-4444-11eb-859f-648bced1e767.png)

**Comment by yanfengliu** [comment]
Hi Zhanqi, 

Thank you for reaching out! I will look into this issue and get back to you soon.

**Comment by ZhanqiZhang66** [comment]
Hi! I figured it out! Thanks Yanfeng

**Comment by yanfengliu** [comment]
No problem. Glad you figured it out!
